stk_admin:
    resource: "@StkAdminBundle/Controller/"
    type: annotation

stk_forum:
    resource: "@StkForumBundle/Controller/"
    type:   annotation

stk_archive:
    resource: "@StkArchiveBundle/Controller/"
    type: annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
